project:
  type: website

website:
  title: "Aaron's Coding and Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aaronpolitsky
      - icon: linkedin
        href: https://www.linkedin.com/in/aaronpolitsky
  google-analytics: "446795634"        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

