project:
  type: website
  output-dir: docs

website:
  title: "quarto_portfolio_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aaronpolitsky
      - icon: linkedin
        href: https://www.linkedin.com/in/aaronpolitsky
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

